### ISSUE TITLE
Nether crashing server every time i join.

### ISSUE THREAD

**Issue by AngryCarrot789** [VoidFlame/Issues#6]
So when i went to spawn for no reason and saw this portal, i went in it, and then the whole server started lagging and crashed. Now every time i join, it crashes the server and lags for everyone.
![2017-09-25_17 54 23](https://user-images.githubusercontent.com/32274404/30821362-05e70222-a21d-11e7-8d27-83d0f74ba624.png)

**Comment by jonsparks** [comment]
This is not limited to when Carrot joins- it's been up and down all day, with no apparent cause in-game for the most part. Certain players do seem to make it happen immediately, but we can also be fine for 15 minutes or so and it randomly craps out without anyone doing something that would cause it. I doubt it's a host issue at this point since HostHorde would have fixed anything shortly after detecting it.

**Comment by AngryCarrot789** [comment]
Update : It's the nether that's broken. JackoPlays_ went in the same portal and the server crashed.

I think you may just need to reset the nether.

**Comment by Jackoooo** [comment]
Reset the nether. please.

**Comment by Jackoooo** [comment]
i can fucking play

**Comment by Jackoooo** [comment]
cant

**Comment by kmecpp** [comment]
Should be fixed now I think? Funny thing is that this happened because I reset the nether.
